include:
  - ./.docker/argcomplete.yaml
  # TODO argcomplete_v1
  - ./.docker/click.yaml
  - ./.docker/cobra.yaml
  - ./.docker/complete.yaml
  - ./.docker/kingpin.yaml
  - ./.docker/urfavecli.yaml
  - ./.docker/urfavecli_v1.yaml
  - ./.docker/yargs.yaml

  - ./.docker/inshellisense.yaml
